@echo off
echo Loading environment variables from .env file...
for /f "tokens=1,2 delims==" %%a in (.env) do set %%a=%%b
echo Running Flutter with environment variables...
flutter run -d chrome --dart-define=API_BASE_URL=%API_BASE_URL% --dart-define=GOOGLE_CLIENT_ID=%GOOGLE_CLIENT_ID%